[package]
name = "prae-macro"
version = "0.1.0"
edition = "2021"
license = "Unlicense"
description = "Proc macro for `prae` crate"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
