[package]
name = "prae"
version = "0.7.0"
edition = "2021"

[features]
default = []
unprocessed = []

[dependencies]
prae-macro = { version = "0.1", path = "../prae-macro" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
